version: 2

updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
      timezone: UTC
    labels:
      - dependencies
      - ruby
    ignore:
      - dependency-name: rubocop*

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
      timezone: UTC
    labels:
      - dependencies
      - javascript
    groups:
      sentry-javascript:
        patterns:
          - "@sentry*"
